import Phaser from '../../lib/phaser.esm.min.js';
import { VIEW_W, VIEW_H } from '../config.js';
import { preloadAudio } from '../audio.js';

/** Loads everything, draws a progress bar, then hands off to the title. */
export default class BootScene extends Phaser.Scene {
    constructor() {
        super('boot');
    }

    preload() {
        this.drawProgressBar();

        // Generated by tools/build_assets.py -- do not edit assets/gen by hand.
        this.load.atlas('atlas', 'assets/gen/atlas.png', 'assets/gen/atlas.json');
        this.load.image('tileset', 'assets/gen/tileset.png');
        this.load.bitmapFont('smw', 'assets/gen/font.png', 'assets/gen/font.xml');

        // Parallax layers, straight from the original rips.
        this.load.image('bg-hills', 'assets/src/01.png');
        this.load.image('bg-clouds', 'assets/src/06.png');

        preloadAudio(this);
    }

    create() {
        this.scene.start('title');
    }

    drawProgressBar() {
        const w = VIEW_W * 0.6;
        const x = (VIEW_W - w) / 2;
        const y = VIEW_H / 2;

        const frame = this.add.rectangle(VIEW_W / 2, y, w + 6, 18)
            .setStrokeStyle(2, 0xffffff);
        const bar = this.add.rectangle(x, y, 0, 12, 0xf8d870).setOrigin(0, 0.5);

        this.load.on('progress', (p) => { bar.width = w * p; });
        this.load.once('complete', () => { frame.destroy(); bar.destroy(); });
    }
}
